### ISSUE TITLE
Bugs in cratedeps

### ISSUE THREAD

**Issue by remilauzier** [decathorpe/miscripts#2]
Erreur : Dépôt inconnu : « rawhide »
Erreur : Dépôt inconnu : « rawhide »

Warning : Unknown repo : « rawhide »

Not sure if it is something on my end. Is there something I should do other than running it with sudo?

**Comment by decathorpe** [comment]
Do you have fedora-repos-rawhide installed? They repositories do not need to be enabled, but the package containing their definitions needs to be installed.

**Comment by decathorpe** [comment]
And the script does not require root privileges.

**Comment by remilauzier** [comment]
Without sudo it bugs on my ends.
Erreur de configuration : [Errno 13] Permission non accordée: '/tmp/dnf/var/tmp': '/tmp/dnf/var/tmp'
conf error. access denied.

But installing the repo as correct my bug, thanks.

**Comment by decathorpe** [comment]
This should only happen if you ran it with sudo first, because then the permissions are messed up and you can't run it without sudo any longer. So removing /tmp/dnf or rebooting should fix running without sudo, I think.

**Comment by remilauzier** [comment]
I check on my computer and the directory doesn't exist. Not sure what's going on.

**Comment by decathorpe** [comment]
Yeah that's the idea. Everything under /tmp is removed every reboot, because it only exists in RAM.

**Comment by remilauzier** [comment]
Yeah but i didn't reboot.

**Comment by remilauzier** [comment]
Reboot fix my problem.
